version: '3'
services:
  blue:
    image: rlaxoqkf/majorfolio:latest
    environment:
      - JAVA_OPTS= -Xmx2g -Xms512m
    container_name: blue
    restart: always
    ports:
      - 8081:8080
  green:
    image: rlaxoqkf/majorfolio:latest
    environment:
      - JAVA_OPTS= -Xmx2g -Xms512m
    container_name: green
    restart: always
    ports:
      - 8082:8080